# Generated by Django 3.2.12 on 2022-11-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='score',
            field=models.FloatField(default='-inf'),
            preserve_default=False,
        ),
    ]
